project.base=wo
project.name=WonderFluffy
project.type=application
principalClass=wonderfluffy.Application
dir.components=Components
dir.woresources=Resources
dir.webserverResources=WebServerResources
